spring:
  application:
    name: tiniProjectBackend
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/tini_db
    username: tini
    password: T!N!2@2b
    hikari:
      max-lifetime: 57000
      maximum-pool-size: 24
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show_sql: true
    defer-datasource-initialization: true

  mongodb:
    uri: mongodb://tiniUser:TlNi0I$@mongoDB:27017/tini_mongodb?authSource=tini_mongodb


jwt:
  secret: vrDt6Hhffv9gPPEEHDBVhxY4W+gf//bxDgVljRr/+8z1ZxqEdgTmDDZ/UIquJuWQdZmJ8mz/DuzLF/pmcMFaqw==
  access_expiration: 1800000
  refresh_expiration: 7776000000

ssh:
  port: 22
  hostname: 3.37.104.158
  username: ec2-user
  password: Tini2@2b

# 소셜 로그인 API 설정
social:
  kakao:
    api-url: https://kapi.kakao.com
    client-id: ${KAKAO_CLIENT_ID:e0ccd9a1366d275242dc304128c7ef03}
    client-secret: ${KAKAO_CLIENT_SECRET:58969640d74f895c291eee6cb53cfa89}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:3000/auth/kakao/callback}
    admin-key: ${KAKAO_ADMIN_KEY:}

